{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":32274,"status":"ok","timestamp":1660646144254,"user":{"displayName":"google coolab","userId":"18259870171034066441"},"user_tz":420},"id":"HtbEuBN5Q2e6","outputId":"ea4eac7d-486b-4294-f3e6-e691857a19bc"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":9593,"status":"ok","timestamp":1660646163875,"user":{"displayName":"google coolab","userId":"18259870171034066441"},"user_tz":420},"id":"-lT_4FzYeH-r","outputId":"c2847e8e-9480-4b15-e973-97940fc5592b"},"outputs":[{"output_type":"stream","name":"stdout","text":["Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting django\n","  Downloading Django-3.2.15-py3-none-any.whl (7.9 MB)\n","\u001b[K     |████████████████████████████████| 7.9 MB 4.2 MB/s \n","\u001b[?25hRequirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from django) (2022.1)\n","Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from django) (0.4.2)\n","Collecting asgiref<4,>=3.3.2\n","  Downloading asgiref-3.5.2-py3-none-any.whl (22 kB)\n","Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from asgiref<4,>=3.3.2->django) (4.1.1)\n","Installing collected packages: asgiref, django\n","Successfully installed asgiref-3.5.2 django-3.2.15\n"]}],"source":["!pip install django"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":1129,"status":"ok","timestamp":1660646182729,"user":{"displayName":"google coolab","userId":"18259870171034066441"},"user_tz":420},"id":"s9jNx1xJP2j5","outputId":"c65ce774-9072-4a47-d562-0e616585db22"},"outputs":[{"output_type":"stream","name":"stdout","text":["/content/drive/MyDrive/Colab Notebooks/OWL\n"]}],"source":["%cd /content/drive/MyDrive/Colab Notebooks/OWL/"]},{"cell_type":"code","execution_count":8,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":35791,"status":"ok","timestamp":1660646622521,"user":{"displayName":"google coolab","userId":"18259870171034066441"},"user_tz":420},"id":"ZQNPuqRAepmv","outputId":"a6c5d152-9b0f-49ce-dd27-9b9fd4c64808"},"outputs":[{"output_type":"stream","name":"stdout","text":["Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Requirement already satisfied: googletrans==3.1.0a0 in /usr/local/lib/python3.7/dist-packages (3.1.0a0)\n","Requirement already satisfied: httpx==0.13.3 in /usr/local/lib/python3.7/dist-packages (from googletrans==3.1.0a0) (0.13.3)\n","Requirement already satisfied: rfc3986<2,>=1.3 in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (1.5.0)\n","Requirement already satisfied: idna==2.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2.10)\n","Requirement already satisfied: hstspreload in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2022.8.1)\n","Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2022.6.15)\n","Requirement already satisfied: sniffio in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (1.2.0)\n","Requirement already satisfied: httpcore==0.9.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (0.9.1)\n","Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (3.0.4)\n","Requirement already satisfied: h11<0.10,>=0.8 in /usr/local/lib/python3.7/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0) (0.9.0)\n","Requirement already satisfied: h2==3.* in /usr/local/lib/python3.7/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0) (3.2.0)\n","Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.7/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0) (5.2.0)\n","Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.7/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0) (3.0.0)\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Requirement already satisfied: pyttsx3 in /usr/local/lib/python3.7/dist-packages (2.90)\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.7/dist-packages (3.8.1)\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Requirement already satisfied: noisereduce in /usr/local/lib/python3.7/dist-packages (2.0.1)\n","Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from noisereduce) (1.7.3)\n","Requirement already satisfied: librosa in /usr/local/lib/python3.7/dist-packages (from noisereduce) (0.8.1)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from noisereduce) (4.64.0)\n","Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from noisereduce) (3.2.2)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from noisereduce) (1.21.6)\n","Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (1.1.0)\n","Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (1.0.2)\n","Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (4.4.2)\n","Requirement already satisfied: pooch>=1.0 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (1.6.0)\n","Requirement already satisfied: numba>=0.43.0 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (0.48.0)\n","Requirement already satisfied: audioread>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (2.1.9)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (21.3)\n","Requirement already satisfied: resampy>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (0.3.1)\n","Requirement already satisfied: soundfile>=0.10.2 in /usr/local/lib/python3.7/dist-packages (from librosa->noisereduce) (0.10.3.post1)\n","Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /usr/local/lib/python3.7/dist-packages (from numba>=0.43.0->librosa->noisereduce) (0.31.0)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from numba>=0.43.0->librosa->noisereduce) (57.4.0)\n","Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->librosa->noisereduce) (3.0.9)\n","Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from pooch>=1.0->librosa->noisereduce) (2.23.0)\n","Requirement already satisfied: appdirs>=1.3.0 in /usr/local/lib/python3.7/dist-packages (from pooch>=1.0->librosa->noisereduce) (1.4.4)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa->noisereduce) (2022.6.15)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa->noisereduce) (2.10)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa->noisereduce) (1.24.3)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa->noisereduce) (3.0.4)\n","Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa->noisereduce) (3.1.0)\n","Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.7/dist-packages (from soundfile>=0.10.2->librosa->noisereduce) (1.15.1)\n","Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.0->soundfile>=0.10.2->librosa->noisereduce) (2.21)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->noisereduce) (0.11.0)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->noisereduce) (1.4.4)\n","Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->noisereduce) (2.8.2)\n","Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->noisereduce) (4.1.1)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib->noisereduce) (1.15.0)\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Requirement already satisfied: webrtcvad in /usr/local/lib/python3.7/dist-packages (2.0.10)\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Requirement already satisfied: django-crispy-forms in /usr/local/lib/python3.7/dist-packages (1.14.0)\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting imageio-ffmpeg\n","  Downloading imageio_ffmpeg-0.4.7-py3-none-manylinux2010_x86_64.whl (26.9 MB)\n","\u001b[K     |████████████████████████████████| 26.9 MB 1.4 MB/s \n","\u001b[?25hInstalling collected packages: imageio-ffmpeg\n","Successfully installed imageio-ffmpeg-0.4.7\n"]}],"source":["!pip install -q -r requirements.txt\n","!apt-get install -qq libportaudio2\n","!pip install googletrans==3.1.0a0\n","!pip install pyttsx3\n","!pip install SpeechRecognition\n","!pip install noisereduce\n","!pip install webrtcvad\n","!pip install django-crispy-forms\n","!pip install imageio-ffmpeg\n"]},{"cell_type":"code","execution_count":5,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"elapsed":4515,"status":"ok","timestamp":1660646342186,"user":{"displayName":"google coolab","userId":"18259870171034066441"},"user_tz":420},"id":"xQ0lVwI1fKCj","outputId":"4b1426e6-2e11-4819-a6dd-e5c25f8be71e"},"outputs":[{"output_type":"stream","name":"stdout","text":["https://vf45iqnh9ar-496ff2e9c6d22116-8000-colab.googleusercontent.com/\n"]}],"source":["from google.colab.output import eval_js\n","print(eval_js(\"google.colab.kernel.proxyPort(8000)\"))"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"0gbrV8jm-U3i","outputId":"fb6e22d9-196a-439d-a663-bff29b9a7f4e"},"outputs":[{"output_type":"stream","name":"stdout","text":["Watching for file changes with StatReloader\n","Performing system checks...\n","\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n","Loaded encoder \"pretrained.pt\" trained to step 1564501\n","Found synthesizer \"pretrained\" trained to step 278000\n","Building Wave-RNN\n","Trainable Parameters: 4.481M\n","Loading model weights at /content/drive/MyDrive/Colab Notebooks/OWL/app/pretrained/vocoder/saved_models/pretrained/pretrained.pt\n","System check identified no issues (0 silenced).\n","August 16, 2022 - 10:48:31\n","Django version 3.2.15, using settings 'OWL.settings'\n","Starting development server at http://127.0.0.1:8000/\n","Quit the server with CONTROL-C.\n","[16/Aug/2022 10:48:38] \u001b[m\"GET / HTTP/1.1\" 200 17880\u001b[0m\n","[16/Aug/2022 10:48:40] \u001b[m\"GET /static/css/maicons.css HTTP/1.1\" 200 43679\u001b[0m\n","[16/Aug/2022 10:48:40] \u001b[m\"GET /static/css/theme.css HTTP/1.1\" 200 40312\u001b[0m\n","[16/Aug/2022 10:48:40] \u001b[m\"GET /static/js/bootstrap.bundle.min.js HTTP/1.1\" 200 81084\u001b[0m\n","[16/Aug/2022 10:48:40] \u001b[m\"GET /static/js/jquery-3.5.1.min.js HTTP/1.1\" 200 89476\u001b[0m\n","[16/Aug/2022 10:48:40] \u001b[m\"GET /static/vendor/wow/wow.min.js HTTP/1.1\" 200 8155\u001b[0m\n","[16/Aug/2022 10:48:40] \u001b[m\"GET /static/vendor/animate/animate.css HTTP/1.1\" 200 77758\u001b[0m\n","[16/Aug/2022 10:48:40] \u001b[m\"GET /static/js/google-maps.js HTTP/1.1\" 200 399\u001b[0m\n","[16/Aug/2022 10:48:41] \u001b[m\"GET /static/js/theme.js HTTP/1.1\" 200 2141\u001b[0m\n","[16/Aug/2022 10:48:41] \u001b[m\"GET /static/css/bootstrap.css HTTP/1.1\" 200 198313\u001b[0m\n","[16/Aug/2022 10:48:41] \u001b[m\"GET /static/img/banner_image_2.svg HTTP/1.1\" 200 27770\u001b[0m\n","[16/Aug/2022 10:48:41] \u001b[m\"GET /static/img/index.png HTTP/1.1\" 200 32797\u001b[0m\n","[16/Aug/2022 10:48:41] \u001b[m\"GET /static/img/aboutUs.png HTTP/1.1\" 200 80040\u001b[0m\n","[16/Aug/2022 10:48:42] \u001b[m\"GET /static/img/services/play-button.png HTTP/1.1\" 200 13525\u001b[0m\n","[16/Aug/2022 10:48:42] \u001b[m\"GET /static/img/services/font.png HTTP/1.1\" 200 9649\u001b[0m\n","[16/Aug/2022 10:48:42] \u001b[m\"GET /static/img/services/microphone.png HTTP/1.1\" 200 22484\u001b[0m\n","Not Found: /assets/img/bg_pattern.svg\n","[16/Aug/2022 10:48:44] \u001b[33m\"GET /assets/img/bg_pattern.svg HTTP/1.1\" 404 4207\u001b[0m\n","[16/Aug/2022 10:48:44] \u001b[m\"GET /static/img/world_pattern.svg HTTP/1.1\" 200 99085\u001b[0m\n","[16/Aug/2022 10:48:44] \u001b[m\"GET /static/img/main.jpg HTTP/1.1\" 200 103063\u001b[0m\n","[16/Aug/2022 10:48:45] \u001b[m\"GET /static/fonts/maicons.ttf?c9nlkl= HTTP/1.1\" 200 268972\u001b[0m\n","Not Found: /favicon.ico\n","[16/Aug/2022 10:48:49] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 4165\u001b[0m\n","[16/Aug/2022 10:49:02] \u001b[m\"GET /login HTTP/1.1\" 200 5755\u001b[0m\n","[16/Aug/2022 10:49:03] \u001b[m\"GET /static/css/maicons.css HTTP/1.1\" 200 43679\u001b[0m\n","[16/Aug/2022 10:49:03] \u001b[m\"GET /static/css/theme.css HTTP/1.1\" 200 40312\u001b[0m\n","[16/Aug/2022 10:49:03] \u001b[m\"GET /static/js/jquery-3.5.1.min.js HTTP/1.1\" 200 89476\u001b[0m\n","[16/Aug/2022 10:49:03] \u001b[m\"GET /static/css/bootstrap.css HTTP/1.1\" 200 198313\u001b[0m\n","[16/Aug/2022 10:49:03] \u001b[m\"GET /static/vendor/animate/animate.css HTTP/1.1\" 200 77758\u001b[0m\n","[16/Aug/2022 10:49:03] \u001b[m\"GET /static/js/bootstrap.bundle.min.js HTTP/1.1\" 200 81084\u001b[0m\n","[16/Aug/2022 10:49:04] \u001b[m\"GET /static/js/theme.js HTTP/1.1\" 200 2141\u001b[0m\n","[16/Aug/2022 10:49:04] \u001b[m\"GET /static/js/google-maps.js HTTP/1.1\" 200 399\u001b[0m\n","[16/Aug/2022 10:49:04] \u001b[m\"GET /static/vendor/wow/wow.min.js HTTP/1.1\" 200 8155\u001b[0m\n","[16/Aug/2022 10:49:04] \u001b[m\"GET /static/img/logn.jpg HTTP/1.1\" 200 67035\u001b[0m\n","[16/Aug/2022 10:49:05] \u001b[m\"GET /static/img/world_pattern.svg HTTP/1.1\" 200 99085\u001b[0m\n","[16/Aug/2022 10:49:05] \u001b[m\"GET /static/fonts/maicons.ttf?c9nlkl= HTTP/1.1\" 200 268972\u001b[0m\n","Not Found: /favicon.ico\n","[16/Aug/2022 10:49:09] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 4165\u001b[0m\n","[16/Aug/2022 10:49:13] \u001b[m\"GET / HTTP/1.1\" 200 17880\u001b[0m\n","[16/Aug/2022 10:49:14] \u001b[m\"GET /static/css/maicons.css HTTP/1.1\" 200 43679\u001b[0m\n","[16/Aug/2022 10:49:15] \u001b[m\"GET /static/css/bootstrap.css HTTP/1.1\" 200 198313\u001b[0m\n","[16/Aug/2022 10:49:15] \u001b[m\"GET /static/vendor/animate/animate.css HTTP/1.1\" 200 77758\u001b[0m\n","[16/Aug/2022 10:49:15] \u001b[m\"GET /static/css/theme.css HTTP/1.1\" 200 40312\u001b[0m\n","[16/Aug/2022 10:49:15] \u001b[m\"GET /static/js/jquery-3.5.1.min.js HTTP/1.1\" 200 89476\u001b[0m\n","[16/Aug/2022 10:49:15] \u001b[m\"GET /static/js/google-maps.js HTTP/1.1\" 200 399\u001b[0m\n","[16/Aug/2022 10:49:15] \u001b[m\"GET /static/vendor/wow/wow.min.js HTTP/1.1\" 200 8155\u001b[0m\n","[16/Aug/2022 10:49:15] \u001b[m\"GET /static/js/theme.js HTTP/1.1\" 200 2141\u001b[0m\n","[16/Aug/2022 10:49:15] \u001b[m\"GET /static/js/bootstrap.bundle.min.js HTTP/1.1\" 200 81084\u001b[0m\n","[16/Aug/2022 10:49:16] \u001b[m\"GET /static/img/aboutUs.png HTTP/1.1\" 200 80040\u001b[0m\n","[16/Aug/2022 10:49:16] \u001b[m\"GET /static/img/banner_image_2.svg HTTP/1.1\" 200 27770\u001b[0m\n","[16/Aug/2022 10:49:16] \u001b[m\"GET /static/img/services/play-button.png HTTP/1.1\" 200 13525\u001b[0m\n","[16/Aug/2022 10:49:16] \u001b[m\"GET /static/img/services/microphone.png HTTP/1.1\" 200 22484\u001b[0m\n","[16/Aug/2022 10:49:16] \u001b[m\"GET /static/img/services/font.png HTTP/1.1\" 200 9649\u001b[0m\n","[16/Aug/2022 10:49:16] \u001b[m\"GET /static/img/index.png HTTP/1.1\" 200 32797\u001b[0m\n","[16/Aug/2022 10:49:19] \u001b[m\"GET /static/img/main.jpg HTTP/1.1\" 200 103063\u001b[0m\n","Not Found: /assets/img/bg_pattern.svg\n","[16/Aug/2022 10:49:19] \u001b[33m\"GET /assets/img/bg_pattern.svg HTTP/1.1\" 404 4207\u001b[0m\n","[16/Aug/2022 10:49:19] \u001b[m\"GET /static/fonts/maicons.ttf?c9nlkl= HTTP/1.1\" 200 268972\u001b[0m\n","[16/Aug/2022 10:49:19] \u001b[m\"GET /static/img/world_pattern.svg HTTP/1.1\" 200 99085\u001b[0m\n","Not Found: /favicon.ico\n","[16/Aug/2022 10:49:22] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 4165\u001b[0m\n","[16/Aug/2022 10:49:35] \u001b[m\"GET /serviceTwo HTTP/1.1\" 200 9144\u001b[0m\n","[16/Aug/2022 10:49:36] \u001b[m\"GET /static/css/maicons.css HTTP/1.1\" 200 43679\u001b[0m\n","[16/Aug/2022 10:49:36] \u001b[m\"GET /static/css/bootstrap.css HTTP/1.1\" 200 198313\u001b[0m\n","[16/Aug/2022 10:49:36] \u001b[m\"GET /static/vendor/animate/animate.css HTTP/1.1\" 200 77758\u001b[0m\n","[16/Aug/2022 10:49:36] \u001b[m\"GET /static/vendor/wow/wow.min.js HTTP/1.1\" 200 8155\u001b[0m\n","[16/Aug/2022 10:49:36] \u001b[m\"GET /static/js/jquery-3.5.1.min.js HTTP/1.1\" 200 89476\u001b[0m\n","[16/Aug/2022 10:49:36] \u001b[m\"GET /static/js/theme.js HTTP/1.1\" 200 2141\u001b[0m\n","[16/Aug/2022 10:49:36] \u001b[m\"GET /static/js/bootstrap.bundle.min.js HTTP/1.1\" 200 81084\u001b[0m\n","[16/Aug/2022 10:49:37] \u001b[m\"GET /static/css/theme.css HTTP/1.1\" 200 40312\u001b[0m\n","[16/Aug/2022 10:49:37] \u001b[m\"GET /static/js/google-maps.js HTTP/1.1\" 200 399\u001b[0m\n","[16/Aug/2022 10:49:39] \u001b[m\"GET /static/img/world_pattern.svg HTTP/1.1\" 200 99085\u001b[0m\n","[16/Aug/2022 10:49:39] \u001b[m\"GET /static/fonts/maicons.ttf?c9nlkl= HTTP/1.1\" 200 268972\u001b[0m\n","[16/Aug/2022 10:49:39] \u001b[m\"GET /static/img/25.png HTTP/1.1\" 200 41687\u001b[0m\n","Not Found: /favicon.ico\n","[16/Aug/2022 10:49:41] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 4165\u001b[0m\n","WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Call initializer instance with the dtype argument instead of passing it to the constructor\n","WARNING:tensorflow:From /content/drive/MyDrive/Colab Notebooks/OWL/app/synthesizer/models/modules.py:113: LSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.\n","WARNING:tensorflow:From /content/drive/MyDrive/Colab Notebooks/OWL/app/synthesizer/models/modules.py:420: conv1d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Use `tf.keras.layers.Conv1D` instead.\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cc848cd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cc848cd0>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:From /content/drive/MyDrive/Colab Notebooks/OWL/app/synthesizer/models/modules.py:421: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).\n","WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cc848cd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cc848cd0>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:From /content/drive/MyDrive/Colab Notebooks/OWL/app/synthesizer/models/modules.py:424: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Use keras.layers.dropout instead.\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69ccd3e250>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69ccd3e250>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cbc5e110>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cbc5e110>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cbcb5e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cbcb5e10>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cbc5ec90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cbc5ec90>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69ccd53610>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69ccd53610>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69ccd53610>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69ccd53610>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69ccc2e990>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69ccc2e990>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:From /content/drive/MyDrive/Colab Notebooks/OWL/app/synthesizer/models/modules.py:234: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API\n","WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/rnn.py:464: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Please use `keras.layers.RNN(cell)`, which is equivalent to this API\n","WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py:961: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Call initializer instance with the dtype argument instead of passing it to the constructor\n","WARNING:tensorflow:Entity <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f69cbc5ead0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f69cbc5ead0>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/rnn.py:244: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Use tf.where in 2.0, which has the same broadcast rule as np.where\n","WARNING:tensorflow:Entity <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f69cbc5ec50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f69cbc5ec50>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cc810e90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cc810e90>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:From /content/drive/MyDrive/Colab Notebooks/OWL/app/synthesizer/models/modules.py:304: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.\n","WARNING:tensorflow:From /content/drive/MyDrive/Colab Notebooks/OWL/app/synthesizer/models/modules.py:268: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Use keras.layers.dense instead.\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cbe54cd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cbe54cd0>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cbe54a50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cbe54a50>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cbe54cd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cbe54cd0>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cc194f50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cc194f50>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7f69cc047990>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7f69cc047990>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f69cc047810>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f69cc047810>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f69cc047f10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f69cc047f10>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cbd4a590>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cbd4a590>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cc1d0550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cc1d0550>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cc1328d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cc1328d0>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cc047a50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cc047a50>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cc194f50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cc194f50>>: AttributeError: module 'gast' has no attribute 'Index'\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cbe54690>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cbe54690>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cbe54690>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cbe54690>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cafe6710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cafe6710>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69caef4650>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69caef4650>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69caef4650>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69caef4650>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69caed9b90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69caed9b90>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cb034350>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cb034350>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cb034350>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cb034350>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cc3c1390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cc3c1390>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69caed9b90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69caed9b90>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69caed9b90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69caed9b90>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69ccc41210>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69ccc41210>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cb03fad0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv1D.call of <tensorflow.python.layers.convolutional.Conv1D object at 0x7f69cb03fad0>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cbcb1090>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f69cbcb1090>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cbcb1090>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f69cbcb1090>>: AttributeError: module 'gast' has no attribute 'Str'\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cbf8f190>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f69cbf8f190>>: AttributeError: module 'gast' has no attribute 'Index'\n","2022-08-16 10:51:11.746832: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2022-08-16 10:51:11.752752: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz\n","2022-08-16 10:51:11.753091: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xd998380 executing computations on platform Host. Devices:\n","2022-08-16 10:51:11.753121: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>\n","2022-08-16 10:51:11.932737: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.\n","WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Use standard file APIs to check for files with this prefix.\n","{| ████████████████ 95000/96000 | Batch Size: 10 | Gen Rate: 1.8kHz | }[16/Aug/2022 10:52:13] \u001b[m\"POST /serviceTwo HTTP/1.1\" 200 5107\u001b[0m\n","[16/Aug/2022 10:52:16] \u001b[m\"GET /static/css/maicons.css HTTP/1.1\" 200 43679\u001b[0m\n","[16/Aug/2022 10:52:16] \u001b[m\"GET /static/css/bootstrap.css HTTP/1.1\" 200 198313\u001b[0m\n","[16/Aug/2022 10:52:17] \u001b[m\"GET /static/vendor/animate/animate.css HTTP/1.1\" 200 77758\u001b[0m\n","[16/Aug/2022 10:52:17] \u001b[m\"GET /static/css/theme.css HTTP/1.1\" 200 40312\u001b[0m\n","[16/Aug/2022 10:52:18] \u001b[m\"GET /static/js/jquery-3.5.1.min.js HTTP/1.1\" 200 89476\u001b[0m\n","[16/Aug/2022 10:52:18] \u001b[m\"GET /static/js/bootstrap.bundle.min.js HTTP/1.1\" 200 81084\u001b[0m\n","[16/Aug/2022 10:52:18] \u001b[m\"GET /static/js/google-maps.js HTTP/1.1\" 200 399\u001b[0m\n","[16/Aug/2022 10:52:19] \u001b[m\"GET /static/fonts/maicons.ttf?c9nlkl= HTTP/1.1\" 200 268972\u001b[0m\n","[16/Aug/2022 10:52:19] \u001b[m\"GET /static/img/25.png HTTP/1.1\" 200 41687\u001b[0m\n","[16/Aug/2022 10:52:19] \u001b[m\"GET /serviceTwo HTTP/1.1\" 200 9144\u001b[0m\n","[16/Aug/2022 10:52:20] \u001b[m\"GET /static/vendor/wow/wow.min.js HTTP/1.1\" 200 8155\u001b[0m\n","[16/Aug/2022 10:52:20] \u001b[m\"GET /static/js/theme.js HTTP/1.1\" 200 2141\u001b[0m\n","[16/Aug/2022 10:52:21] \u001b[m\"GET /static/img/world_pattern.svg HTTP/1.1\" 200 99085\u001b[0m\n","Not Found: /favicon.ico\n","[16/Aug/2022 10:52:23] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 4165\u001b[0m\n","[16/Aug/2022 10:52:30] \u001b[m\"GET /media/bot.wav HTTP/1.1\" 200 203644\u001b[0m\n"]}],"source":["!python manage.py runserver 8000"]},{"cell_type":"code","execution_count":11,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":12612,"status":"ok","timestamp":1660646884793,"user":{"displayName":"google coolab","userId":"18259870171034066441"},"user_tz":420},"id":"SCgyD4VNfxAT","outputId":"4936ae09-ffdd-4daa-f6b6-5acebf5fcc0e"},"outputs":[{"output_type":"stream","name":"stdout","text":["Exception ignored in: <function Local.__del__ at 0x7f204f176320>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/asgiref/local.py\", line 87, in __del__\n","    def __del__(self):\n","KeyboardInterrupt\n","Traceback (most recent call last):\n","  File \"manage.py\", line 22, in <module>\n","    main()\n","  File \"manage.py\", line 18, in main\n","    execute_from_command_line(sys.argv)\n","  File \"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py\", line 419, in execute_from_command_line\n","    utility.execute()\n","  File \"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py\", line 413, in execute\n","    self.fetch_command(subcommand).run_from_argv(self.argv)\n","  File \"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py\", line 354, in run_from_argv\n","    self.execute(*args, **cmd_options)\n","  File \"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py\", line 393, in execute\n","    self.check()\n","  File \"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py\", line 423, in check\n","    databases=databases,\n","  File \"/usr/local/lib/python3.7/dist-packages/django/core/checks/registry.py\", line 76, in run_checks\n","    new_errors = check(app_configs=app_configs, databases=databases)\n","  File \"/usr/local/lib/python3.7/dist-packages/django/core/checks/urls.py\", line 40, in check_url_namespaces_unique\n","    all_namespaces = _load_all_namespaces(resolver)\n","  File \"/usr/local/lib/python3.7/dist-packages/django/core/checks/urls.py\", line 57, in _load_all_namespaces\n","    url_patterns = getattr(resolver, 'url_patterns', [])\n","  File \"/usr/local/lib/python3.7/dist-packages/django/utils/functional.py\", line 48, in __get__\n","    res = instance.__dict__[self.name] = self.func(instance)\n","  File \"/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py\", line 602, in url_patterns\n","    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n","  File \"/usr/local/lib/python3.7/dist-packages/django/utils/functional.py\", line 48, in __get__\n","    res = instance.__dict__[self.name] = self.func(instance)\n","  File \"/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py\", line 595, in urlconf_module\n","    return import_module(self.urlconf_name)\n","  File \"/usr/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n","  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n","  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n","  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","  File \"/content/drive/MyDrive/Colab Notebooks/OWL/OWL/urls.py\", line 24, in <module>\n","    path('',include('app.urls')),\n","  File \"/usr/local/lib/python3.7/dist-packages/django/urls/conf.py\", line 34, in include\n","    urlconf_module = import_module(urlconf_module)\n","  File \"/usr/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n","  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n","  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n","  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","  File \"/content/drive/MyDrive/Colab Notebooks/OWL/app/urls.py\", line 2, in <module>\n","    from app import views\n","  File \"/content/drive/MyDrive/Colab Notebooks/OWL/app/views.py\", line 14, in <module>\n","    import librosa\n","  File \"/usr/local/lib/python3.7/dist-packages/librosa/__init__.py\", line 211, in <module>\n","    from . import core\n","  File \"/usr/local/lib/python3.7/dist-packages/librosa/core/__init__.py\", line 6, in <module>\n","    from .audio import *  # pylint: disable=wildcard-import\n","  File \"/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py\", line 12, in <module>\n","    import resampy\n","  File \"/usr/local/lib/python3.7/dist-packages/resampy/__init__.py\", line 7, in <module>\n","    from .core import *\n","  File \"/usr/local/lib/python3.7/dist-packages/resampy/core.py\", line 9, in <module>\n","    from .interpn import resample_f_s, resample_f_p\n","  File \"/usr/local/lib/python3.7/dist-packages/resampy/interpn.py\", line 144, in <module>\n","    nopython=True,\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/npyufunc/decorators.py\", line 179, in wrap\n","    guvec.add(fty)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/npyufunc/ufuncbuilder.py\", line 215, in add\n","    self.nb_func, targetoptions, sig)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/npyufunc/ufuncbuilder.py\", line 146, in _compile_element_wise_function\n","    cres = nb_func.compile(sig, **targetoptions)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/npyufunc/ufuncbuilder.py\", line 95, in compile\n","    return self._compile_core(sig, flags, locals)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/npyufunc/ufuncbuilder.py\", line 130, in _compile_core\n","    flags=flags, locals=locals)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler.py\", line 551, in compile_extra\n","    return pipeline.compile_extra(func)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler.py\", line 331, in compile_extra\n","    return self._compile_bytecode()\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler.py\", line 393, in _compile_bytecode\n","    return self._compile_core()\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler.py\", line 364, in _compile_core\n","    pm.run(self.state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py\", line 338, in run\n","    self._runPass(idx, pass_inst, state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_lock.py\", line 32, in _acquire_compile_lock\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py\", line 302, in _runPass\n","    mutated |= check(pss.run_pass, internal_state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py\", line 275, in check\n","    mangled = func(compiler_state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typed_passes.py\", line 95, in run_pass\n","    raise_errors=self._raise_errors)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typed_passes.py\", line 67, in type_inference_stage\n","    infer.propagate(raise_errors=raise_errors)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typeinfer.py\", line 977, in propagate\n","    errors = self.constraints.propagate(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typeinfer.py\", line 148, in propagate\n","    constraint(typeinfer)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typeinfer.py\", line 486, in __call__\n","    self.resolve(typeinfer, typevars, fnty)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typeinfer.py\", line 506, in resolve\n","    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typeinfer.py\", line 1440, in resolve_call\n","    return self.context.resolve_function_type(fnty, pos_args, kw_args)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typing/context.py\", line 199, in resolve_function_type\n","    res = self._resolve_user_function_type(func, args, kws)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typing/context.py\", line 251, in _resolve_user_function_type\n","    return func.get_call_type(self, args, kws)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/types/functions.py\", line 274, in get_call_type\n","    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py\", line 301, in get_call_template\n","    self.compile(tuple(args))\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_lock.py\", line 32, in _acquire_compile_lock\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py\", line 768, in compile\n","    cres = self._compiler.compile(args, return_type)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py\", line 77, in compile\n","    status, retval = self._compile_cached(args, return_type)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py\", line 91, in _compile_cached\n","    retval = self._compile_core(args, return_type)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py\", line 109, in _compile_core\n","    pipeline_class=self.pipeline_class)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler.py\", line 551, in compile_extra\n","    return pipeline.compile_extra(func)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler.py\", line 331, in compile_extra\n","    return self._compile_bytecode()\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler.py\", line 393, in _compile_bytecode\n","    return self._compile_core()\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler.py\", line 364, in _compile_core\n","    pm.run(self.state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py\", line 338, in run\n","    self._runPass(idx, pass_inst, state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_lock.py\", line 32, in _acquire_compile_lock\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py\", line 302, in _runPass\n","    mutated |= check(pss.run_pass, internal_state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py\", line 275, in check\n","    mangled = func(compiler_state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typed_passes.py\", line 407, in run_pass\n","    NativeLowering().run_pass(state)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/typed_passes.py\", line 351, in run_pass\n","    lower.create_cpython_wrapper(flags.release_gil)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/lowering.py\", line 302, in create_cpython_wrapper\n","    release_gil=release_gil)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/targets/cpu.py\", line 162, in create_cpython_wrapper\n","    builder.build()\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/callwrapper.py\", line 124, in build\n","    self.build_wrapper(api, builder, closure, args, kws)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/callwrapper.py\", line 165, in build_wrapper\n","    innerargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/numba/targets/callconv.py\", line 538, in call_function\n","    code = builder.call(callee, realargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/llvmlite/ir/builder.py\", line 841, in call\n","    cconv=cconv, tail=tail, fastmath=fastmath)\n","  File \"/usr/local/lib/python3.7/dist-packages/llvmlite/ir/instructions.py\", line 88, in __init__\n","    \"call\", [func] + list(args), name=name)\n","  File \"/usr/local/lib/python3.7/dist-packages/llvmlite/ir/instructions.py\", line 21, in __init__\n","    self.metadata = {}\n","KeyboardInterrupt\n"]}],"source":["!python manage.py makemigrations"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"ouGAxqHdI2R3","outputId":"29f410b4-ac9f-4fdd-9020-fa4d9e527af5"},"outputs":[{"name":"stdout","output_type":"stream","text":["/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n","/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n","  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n","Loaded encoder \"pretrained.pt\" trained to step 1564501\n","Found synthesizer \"pretrained\" trained to step 278000\n","Building Wave-RNN\n","Trainable Parameters: 4.481M\n","Loading model weights at /content/drive/MyDrive/Colab Notebooks/OWL/app/pretrained/vocoder/saved_models/pretrained/pretrained.pt\n","\u001b[36;1mOperations to perform:\u001b[0m\n","\u001b[1m  Apply all migrations: \u001b[0madmin, app, auth, contenttypes, sessions\n","\u001b[36;1mRunning migrations:\u001b[0m\n","  No migrations to apply.\n"]}],"source":["!python manage.py migrate"]},{"cell_type":"markdown","metadata":{"id":"TNa1VCWORBIX"},"source":[""]},{"cell_type":"code","execution_count":null,"metadata":{"id":"aisfaHKAeYva"},"outputs":[],"source":["%cd ..\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"HjWE5LA4A6_s"},"outputs":[],"source":["%cd Real-Time-Voice-Cloning"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ZZwDUNPfAnPV"},"outputs":[],"source":["!git clone https://github.com/misbah4064/Real-Time-Voice-Cloning.git"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"RILXar-leZl5"},"outputs":[],"source":["!django-admin startproject OWL"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"gMrxXPHOhJKc"},"outputs":[],"source":["!django-admin startapp app"]}],"metadata":{"colab":{"collapsed_sections":[],"name":"Copy of project owl web.ipynb","provenance":[{"file_id":"1tMhQvfWmBTP-w0b_d4-TLNs1w5lhfoun","timestamp":1649156914248}]},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}